import { collection, addDoc, Timestamp } from 'firebase/firestore';
import { db } from '../firebase';

// Sample data generator for Judge Dashboard

export const generateSampleCases = async (judgeId: string, judgeName: string) => {
  const sampleCases = [
    {
      caseNumber: 'CC-DLI-12345/2026',
      caseType: 'criminal',
      caseTitle: 'State of Delhi vs Rajesh Kumar',
      petitioner: {
        name: 'State of Delhi',
        type: 'government',
        address: 'Delhi High Court, New Delhi',
        lawyerName: 'Advocate Priya Sharma',
      },
      respondent: {
        name: 'Rajesh Kumar',
        type: 'individual',
        address: 'Block C, Dwarka, New Delhi',
        phone: '+91 98765 43210',
        lawyerName: 'Advocate Anil Verma',
      },
      status: 'under_trial',
      priority: 'high',
      judgeId,
      judgeName,
      courtId: 'DLI-01',
      courtName: 'District Court, New Delhi',
      filingDate: Timestamp.fromDate(new Date('2026-01-15')),
      nextHearingDate: Timestamp.fromDate(new Date('2026-02-15')),
      synopsis: 'Case involving allegations of fraud and misappropriation of funds amounting to Rs. 50 lakhs. Investigation revealed forged documents and false representations.',
      ipcSections: ['IPC 420', 'IPC 406', 'IPC 468'],
      totalHearings: 5,
      completedHearings: 3,
      adjournmentCount: 1,
      documentIds: [],
      isConfidential: false,
      tags: ['fraud', 'financial'],
      createdAt: Timestamp.fromDate(new Date('2026-01-15')),
      updatedAt: Timestamp.now(),
      createdBy: judgeId,
      lastModifiedBy: judgeId,
    },
    {
      caseNumber: 'FM-DLI-99001/2026',
      caseType: 'family',
      caseTitle: 'Anjali Gupta vs Vikram Gupta',
      petitioner: {
        name: 'Anjali Gupta',
        type: 'individual',
        address: 'Sector 18, Noida',
        phone: '+91 98888 12345',
        lawyerName: 'Advocate Meera Singh',
      },
      respondent: {
        name: 'Vikram Gupta',
        type: 'individual',
        address: 'Greater Kailash, New Delhi',
        phone: '+91 98777 54321',
        lawyerName: 'Advocate Rajiv Khanna',
      },
      status: 'arguments_completed',
      priority: 'normal',
      judgeId,
      judgeName,
      courtId: 'DLI-01',
      courtName: 'District Court, New Delhi',
      filingDate: Timestamp.fromDate(new Date('2025-11-20')),
      nextHearingDate: Timestamp.fromDate(new Date('2026-02-18')),
      synopsis: 'Divorce petition filed on grounds of cruelty and incompatibility. Child custody and alimony matters to be decided.',
      totalHearings: 8,
      completedHearings: 7,
      adjournmentCount: 2,
      documentIds: [],
      isConfidential: true,
      tags: ['divorce', 'custody'],
      createdAt: Timestamp.fromDate(new Date('2025-11-20')),
      updatedAt: Timestamp.now(),
      createdBy: judgeId,
      lastModifiedBy: judgeId,
    },
    {
      caseNumber: 'CV-DLI-45678/2026',
      caseType: 'civil',
      caseTitle: 'M/s Tech Solutions vs Alpha Enterprises',
      petitioner: {
        name: 'M/s Tech Solutions Pvt Ltd',
        type: 'organization',
        address: 'Cyber City, Gurgaon',
        lawyerName: 'Advocate Suresh Patel',
      },
      respondent: {
        name: 'Alpha Enterprises Ltd',
        type: 'organization',
        address: 'Connaught Place, New Delhi',
        lawyerName: 'Advocate Kavita Malhotra',
      },
      status: 'pending_evidence',
      priority: 'urgent',
      judgeId,
      judgeName,
      courtId: 'DLI-01',
      courtName: 'District Court, New Delhi',
      filingDate: Timestamp.fromDate(new Date('2026-02-01')),
      nextHearingDate: Timestamp.fromDate(new Date('2026-02-12')),
      synopsis: 'Breach of contract dispute regarding software development agreement. Plaintiff seeking damages of Rs. 2 crores for non-payment and contract violations.',
      totalHearings: 2,
      completedHearings: 1,
      adjournmentCount: 0,
      documentIds: [],
      isConfidential: false,
      tags: ['contract', 'commercial'],
      createdAt: Timestamp.fromDate(new Date('2026-02-01')),
      updatedAt: Timestamp.now(),
      createdBy: judgeId,
      lastModifiedBy: judgeId,
    },
    {
      caseNumber: 'CR-DLI-78910/2025',
      caseType: 'criminal',
      caseTitle: 'State of Delhi vs Mohit Sharma & Ors',
      petitioner: {
        name: 'State of Delhi',
        type: 'government',
        address: 'Delhi High Court, New Delhi',
        lawyerName: 'Public Prosecutor K.R. Menon',
      },
      respondent: {
        name: 'Mohit Sharma & 2 Others',
        type: 'individual',
        address: 'Rohini, New Delhi',
        lawyerName: 'Advocate Deepak Rao',
      },
      status: 'reserved_for_judgment',
      priority: 'high',
      judgeId,
      judgeName,
      courtId: 'DLI-01',
      courtName: 'District Court, New Delhi',
      filingDate: Timestamp.fromDate(new Date('2025-09-10')),
      synopsis: 'Case involving organized theft ring. Evidence presented includes CCTV footage, witness testimonies, and recovered stolen goods.',
      ipcSections: ['IPC 379', 'IPC 411', 'IPC 120B'],
      totalHearings: 12,
      completedHearings: 12,
      adjournmentCount: 3,
      documentIds: [],
      isConfidential: false,
      tags: ['theft', 'organized crime'],
      createdAt: Timestamp.fromDate(new Date('2025-09-10')),
      updatedAt: Timestamp.now(),
      createdBy: judgeId,
      lastModifiedBy: judgeId,
    },
    {
      caseNumber: 'CS-DLI-11223/2026',
      caseType: 'consumer',
      caseTitle: 'Ramesh Chand vs XYZ Bank Ltd',
      petitioner: {
        name: 'Ramesh Chand',
        type: 'individual',
        address: 'Lajpat Nagar, New Delhi',
        phone: '+91 98111 22333',
        lawyerName: 'Advocate Sanjay Kumar',
      },
      respondent: {
        name: 'XYZ Bank Ltd',
        type: 'organization',
        address: 'Barakhamba Road, New Delhi',
        lawyerName: 'Advocate Nisha Kapoor',
      },
      status: 'adjourned',
      priority: 'normal',
      judgeId,
      judgeName,
      courtId: 'DLI-01',
      courtName: 'District Court, New Delhi',
      filingDate: Timestamp.fromDate(new Date('2026-01-28')),
      nextHearingDate: Timestamp.fromDate(new Date('2026-02-20')),
      synopsis: 'Consumer complaint regarding unauthorized debit transactions and deficiency in banking services. Compensation sought for financial loss and mental harassment.',
      totalHearings: 3,
      completedHearings: 2,
      adjournmentCount: 1,
      documentIds: [],
      isConfidential: false,
      tags: ['banking', 'consumer rights'],
      createdAt: Timestamp.fromDate(new Date('2026-01-28')),
      updatedAt: Timestamp.now(),
      createdBy: judgeId,
      lastModifiedBy: judgeId,
    },
  ];

  const createdCases = [];
  for (const caseData of sampleCases) {
    const docRef = await addDoc(collection(db, 'cases'), caseData);
    createdCases.push({ id: docRef.id, ...caseData });
  }
  
  return createdCases;
};

export const generateSampleHearings = async (judgeId: string, judgeName: string) => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  const getDate = (daysFromToday: number) => {
    const date = new Date(today);
    date.setDate(date.getDate() + daysFromToday);
    return Timestamp.fromDate(date);
  };

  const sampleHearings = [
    // Today's hearings
    {
      caseId: 'mock-case-1',
      caseNumber: 'CC-DLI-12345/2026',
      caseTitle: 'State of Delhi vs Rajesh Kumar',
      hearingDate: getDate(0),
      hearingTime: '10:30 AM',
      courtRoomNumber: '3',
      judgeId,
      judgeName,
      partiesPresent: ['State Counsel', 'Defendant'],
      lawyersPresent: ['Adv. Priya Sharma', 'Adv. Anil Verma'],
      purpose: 'Evidence',
      notes: 'Prosecution to present documentary evidence',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: ['evidence-doc-1', 'evidence-doc-2'],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    {
      caseId: 'mock-case-2',
      caseNumber: 'FM-DLI-99001/2026',
      caseTitle: 'Anjali Gupta vs Vikram Gupta',
      hearingDate: getDate(0),
      hearingTime: '02:00 PM',
      courtRoomNumber: '2',
      judgeId,
      judgeName,
      partiesPresent: ['Petitioner', 'Respondent'],
      lawyersPresent: ['Adv. Meera Singh', 'Adv. Rajiv Khanna'],
      purpose: 'Arguments',
      notes: 'Final arguments on custody matter',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    {
      caseId: 'mock-case-3',
      caseNumber: 'CV-DLI-45678/2026',
      caseTitle: 'M/s Tech Solutions vs Alpha Enterprises',
      hearingDate: getDate(0),
      hearingTime: '04:15 PM',
      courtRoomNumber: '3',
      judgeId,
      judgeName,
      partiesPresent: ['Plaintiff Rep', 'Defendant Rep'],
      lawyersPresent: ['Adv. Suresh Patel', 'Adv. Kavita Malhotra'],
      purpose: 'Interim Application',
      notes: 'Application for interim injunction',
      outcome: 'completed',
      isSuccessful: false,
      documentsSubmitted: ['application-doc'],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    
    // Tomorrow's hearings
    {
      caseId: 'mock-case-4',
      caseNumber: 'CR-DLI-78910/2025',
      caseTitle: 'State of Delhi vs Mohit Sharma & Ors',
      hearingDate: getDate(1),
      hearingTime: '11:00 AM',
      courtRoomNumber: '1',
      judgeId,
      judgeName,
      partiesPresent: [],
      lawyersPresent: [],
      purpose: 'Judgment',
      notes: 'Pronouncement of judgment',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    
    // Next week hearings
    {
      caseId: 'mock-case-5',
      caseNumber: 'CV-DLI-45678/2026',
      caseTitle: 'M/s Tech Solutions vs Alpha Enterprises',
      hearingDate: getDate(2),
      hearingTime: '10:00 AM',
      courtRoomNumber: '3',
      judgeId,
      judgeName,
      partiesPresent: [],
      lawyersPresent: [],
      purpose: 'Evidence',
      notes: 'Plaintiff to present expert witness',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    {
      caseId: 'mock-case-6',
      caseNumber: 'CC-DLI-12345/2026',
      caseTitle: 'State of Delhi vs Rajesh Kumar',
      hearingDate: getDate(5),
      hearingTime: '03:30 PM',
      courtRoomNumber: '2',
      judgeId,
      judgeName,
      partiesPresent: [],
      lawyersPresent: [],
      purpose: 'Arguments',
      notes: 'Defense final arguments',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    {
      caseId: 'mock-case-7',
      caseNumber: 'FM-DLI-99001/2026',
      caseTitle: 'Anjali Gupta vs Vikram Gupta',
      hearingDate: getDate(8),
      hearingTime: '11:30 AM',
      courtRoomNumber: '1',
      judgeId,
      judgeName,
      partiesPresent: [],
      lawyersPresent: [],
      purpose: 'Final Hearing',
      notes: 'Final decision on divorce and custody',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    {
      caseId: 'mock-case-8',
      caseNumber: 'CS-DLI-11223/2026',
      caseTitle: 'Ramesh Chand vs XYZ Bank Ltd',
      hearingDate: getDate(10),
      hearingTime: '02:30 PM',
      courtRoomNumber: '2',
      judgeId,
      judgeName,
      partiesPresent: [],
      lawyersPresent: [],
      purpose: 'Evidence',
      notes: 'Bank to submit transaction records',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    
    // Later hearings
    {
      caseId: 'mock-case-9',
      caseNumber: 'CC-DLI-12345/2026',
      caseTitle: 'State of Delhi vs Rajesh Kumar',
      hearingDate: getDate(15),
      hearingTime: '10:00 AM',
      courtRoomNumber: '3',
      judgeId,
      judgeName,
      partiesPresent: [],
      lawyersPresent: [],
      purpose: 'Final Hearing',
      notes: 'Final hearing and judgment',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    {
      caseId: 'mock-case-10',
      caseNumber: 'FM-DLI-99001/2026',
      caseTitle: 'Anjali Gupta vs Vikram Gupta',
      hearingDate: getDate(18),
      hearingTime: '01:00 PM',
      courtRoomNumber: '1',
      judgeId,
      judgeName,
      partiesPresent: [],
      lawyersPresent: [],
      purpose: 'Judgment',
      notes: 'Pronouncement of final order',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
    {
      caseId: 'mock-case-11',
      caseNumber: 'CS-DLI-11223/2026',
      caseTitle: 'Ramesh Chand vs XYZ Bank Ltd',
      hearingDate: getDate(20),
      hearingTime: '11:00 AM',
      courtRoomNumber: '2',
      judgeId,
      judgeName,
      partiesPresent: [],
      lawyersPresent: [],
      purpose: 'Arguments',
      notes: 'Final arguments and submissions',
      outcome: 'completed',
      isSuccessful: true,
      documentsSubmitted: [],
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      recordedBy: judgeId,
    },
  ];

  const createdHearings = [];
  for (const hearingData of sampleHearings) {
    const docRef = await addDoc(collection(db, 'hearings'), hearingData);
    createdHearings.push({ id: docRef.id, ...hearingData });
  }
  
  return createdHearings;
};

export const initializeSampleData = async (judgeId: string, judgeName: string) => {
  try {
    console.log('Initializing sample court data...');
    
    const cases = await generateSampleCases(judgeId, judgeName);
    console.log(`✅ Created ${cases.length} sample cases`);
    
    const hearings = await generateSampleHearings(judgeId, judgeName);
    console.log(`✅ Created ${hearings.length} sample hearings`);
    
    return {
      cases,
      hearings,
      success: true,
      message: `Successfully created ${cases.length} cases and ${hearings.length} hearings`,
    };
  } catch (error) {
    console.error('Error initializing sample data:', error);
    return {
      cases: [],
      hearings: [],
      success: false,
      message: `Error: ${error}`,
    };
  }
};
